use_frameworks!

platform :ios, '10.0'

target 'NQNotification_Example' do
  pod 'NQNotification', :path => '../'

  target 'NQNotification_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
